### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by nleiva** [nornir-automation/gornir#10]
Or anything similar to validate the code is still passing all the test cases. I know might the API is still in its early days, but enforcing testing early on will surely pay dividends in the long run.

**Comment by dbarrosop** [comment]
Yeah, at a minimum I want to start by testing the examples using a golden file pattern, even if it's just running them from bash, dumping the output to a file and ensuring there is no diff between the golden file and the new output.

Once the API is a bit more stable we can start adding tests for the public interface.

**Comment by dbarrosop** [comment]
This is fixed now.
