### ISSUE TITLE
add a NullLogger or similar

### ISSUE THREAD

**Issue by dbarrosop** [nornir-automation/gornir#15]
Right now we have a logrus logger, it'd be nice to add a null one in case people doesn't want logs.

**Comment by nleiva** [comment]
Right. I was thinking the `log` from the standard library would be a good default, but I think this is probably better as there might be cases you actually don't want to log.

I think this is a simple addition, so I will leave it for a newcomer. All that is required is creating a concrete type that satisfies the Logger interface. All its methods could be empty.

**Comment by dbarrosop** [comment]
oh, missed your comment, I already opened a PR. I think a plugin that wraps around the standard `log` package might still be useful for some people.
