### ISSUE TITLE
enhancement discussion 

### ISSUE THREAD

**Issue by Ali-aqrabawi** [nornir-automation/gornir#36]
i would love to see a network automation tool that has everything running concurrently, 
for example:
you can have two channels `JobsChan` and `ResultsChan`, then a readers reads `inventory` and `playbooks` and start sending `Jobs` on `'JobsChan`.

on the other side you have the `Runner` that fetch `Jobs` and spawn a task that execute them and send the results to `ResultsChan`.

and finally you have the a the `ResultHandler` that pull results from `ResultsChan` and send them to the output `fds` weather an `stdout` or `file`. 
do you think this will have added Value? or you think this approach is not really needed in network automation as you don't expect huge inventory/play files?

**Comment by dbarrosop** [comment]
I am not sure I understand what you mean but I suppose what you described is this example:

https://github.com/nornir-automation/gornir/blob/master/examples/5_advanced_2/main.go

**Comment by Ali-aqrabawi** [comment]
yeah this example implement the `ResultChan` but also i suggest to have a `JobsChan` that will be emitted by the `inventory/plays`, also it would be nice if gornir provide a `cli` utility where users should provide `inventory` and `play` same as in ansible,
