### ISSUE TITLE
Is gonir alive?

### ISSUE THREAD

**Issue by denysaleksandrov** [nornir-automation/gornir#47]
Hey folks, 
is this project alive? 3 months no commits.
If so, could you please provide a Contribution Guidelines? Something similar to the nornir's Contribution Guidelines would be much appreciated.

**Comment by dbarrosop** [comment]
As far as I am concerned it is alive. As a matter of fact, I rely heavily on it in production. Reason why there has been no commits is because the core has proven stable and the tasks I am using are custom-made as they are all consuming grpc services.

I will add some contributing guidelines (thanks for the reminder), in the meantime, if you are planning contributions let me know here and I will help you.

Thanks

**Comment by denysaleksandrov** [comment]
Thanks for the prompt reply. 
Yes, I definitely want to contribute. Let me try and test it in my network. 
I want to add first an inventory plugin which gets hosts/devices from an api. We have a db with all devices stored there. I don't see a point to write YAML files while I can get all I need using a simple api call. 

Could you please elaborate more on "the tasks I am using are custom-made as they are all consuming grpc services." ?

**Comment by dbarrosop** [comment]
> Could you please elaborate more on "the tasks I am using are custom-made as they are all consuming grpc services." ?

They are internal services so nothing that could be opensourced

**Comment by cisgoio** [comment]
hey guys,
are the contribution guidelines public? In my project, I am in the process of using nornir and scrapli, over ansible for obvious reasons :-) Lucky, I just came across your project after seeing it mentioned at ciscolive. This, I can work on while automating nexus and compare both frameworks. We all know though, Golang is the magical sword :-D So I'd like to contribute. kr, Scott

**Comment by dbarrosop** [comment]
There are no specific contributing guidelines for this project but should be similar to the ones for [nornir](https://github.com/nornir-automation/nornir/blob/develop/CONTRIBUTING.rst) (except the python/golang specific bits)

I am also closing this issue as there is nothing to do here I feel.
