### ISSUE TITLE
Use of Context

### ISSUE THREAD

**Issue by nleiva** [nornir-automation/gornir#6]
Hi, I would personally prefer to avoid wrapping the Context in another Context struct for two reasons. 

1.  Context does provide a mechanism to store values already, however is recommended to "_Cnly use context.Value for data that can’t be passed through your program in any other way. In practice, this means only using context.Value for request-scoped information, like request IDs, user authentication tokens, and so on_". [SOURCE](https://peter.bourgon.org/go-for-industrial-programming/#context-use-and-misuse)

```go
type Context struct {
	ctx    context.Context
	title  string
	id     string
	gr     *Gornir
	logger Logger
	host   *Host
}
```

2. You are passing these values explicitly to the runner functions anyways.

```go
func (g *Gornir) RunA(title string, runner Runner, task Task, results chan *JobResult) error {
	err := runner.Run(
		NewContext(context.Background(), title, g, g.Logger),
		task,
		results,
	)
	...
}
```

Let me know if I'm missing anything. Also, if you embed the context.Context all its methods get promoted so you don't really need to reimplement everything to satisfy the interface.

**Comment by dbarrosop** [comment]
Yeah, I think you are right. It's probably worth looking into decoupling the context and passing the parameters that need to be passed around explicitly.

Thanks for the feedback :)

**Comment by dbarrosop** [comment]
Mocked very quickly a PR addressing this, I don't think it's ready but wanted to open it to discuss the API.

**Comment by nleiva** [comment]
LGTM. I added some general comments about the code.

**Comment by dbarrosop** [comment]
This one is addressed I think so I am closing it, if there is anything else you want to discuss feel free to reopen.
